<?php
include('../../../inc/includes.php');
Session::checkLoginUser();
require_once(__DIR__ . '/../inc/permissions.php');
require_once(__DIR__ . '/../inc/config.php');
require_once(__DIR__ . '/../inc/assets_helpers.php');

$root = $CFG_GLPI['root_doc'] ?? '';
$version = defined('PLUGIN_SCHOOLMANAGER_VERSION') ? PLUGIN_SCHOOLMANAGER_VERSION : '1.2.1';
$logoUrl = plugin_schoolmanager_logo_url();
$mode = plugin_schoolmanager_user_mode();
$canTickets = plugin_schoolmanager_can_create_ticket();
$canAssets = plugin_schoolmanager_can_create_asset(null);
$canStock = function_exists('plugin_schoolmanager_can_manage_stock') ? plugin_schoolmanager_can_manage_stock() : $canAssets;
$canSuper = function_exists('smgr_is_super_admin_user') && smgr_is_super_admin_user();
$canTicAssign = function_exists('smgr_can_manage_tic_assignments') ? smgr_can_manage_tic_assignments() : $canSuper;
$isAdminTic = function_exists('smgr_user_has_admin_tic_profile') && smgr_user_has_admin_tic_profile((int)Session::getLoginUserID());
$isTicTech = function_exists('smgr_user_has_tecnico_tic_profile') && smgr_user_has_tecnico_tic_profile((int)Session::getLoginUserID());
if (($canStock || $canAssets || $isTicTech || $isAdminTic) && $mode === 'profesor') { $mode = 'tecnico'; }
Html::header(plugin_schoolmanager_app_name(), $_SERVER['PHP_SELF'], 'tools', 'PluginSchoolmanagerMapa');
function smhome_h($v){return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');}
function smhome_url($path){global $root,$version; $sep=strpos($path,'?')===false?'?':'&'; return $root.$path.$sep.'v='.rawurlencode($version);} 
function smhome_icon($name){$icons=['ticket'=>'<path d="M5 7.5h14v3a2 2 0 0 0 0 4v3H5v-3a2 2 0 0 0 0-4v-3Z"/><path d="M9 8v8M15 8v8"/>','check'=>'<path d="M4.5 12.5 9.2 17 19.5 7"/>','bell'=>'<path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 7h18s-3 0-3-7"/><path d="M10 20a2.4 2.4 0 0 0 4 0"/>','plus'=>'<path d="M12 5v14M5 12h14"/>','tools'=>'<path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L4.8 16.2a2 2 0 0 0 2.8 2.8l4.5-4.5a4 4 0 0 0 5.5-5.2l-2.7 2.7-2.2-2.2 2.7-2.7Z"/>','stock'=>'<rect x="5" y="4" width="14" height="6" rx="2"/><rect x="5" y="14" width="14" height="6" rx="2"/><path d="M8 7h.01M8 17h.01M12 10v4M9 12h6"/>','map'=>'<path d="M9 18 3.5 20V6l5.5-2 6 2 5.5-2v14l-5.5 2-6-2Z"/><path d="M9 4v14M15 6v14"/>','list'=>'<path d="M8 6h12M8 12h12M8 18h12"/><path d="M4 6h.01M4 12h.01M4 18h.01"/>','chart'=>'<path d="M4 19V5"/><path d="M8 17V9M13 17V5M18 17v-6"/><path d="M3 19h18"/>','note'=>'<path d="M6 3h9l3 3v15H6V3Z"/><path d="M14 3v4h4"/><path d="M9 12h6M9 16h6"/>','clock'=>'<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3 2"/>']; $body=$icons[$name]??$icons['note']; return '<svg class="sm-svg" viewBox="0 0 24 24" fill="none" aria-hidden="true">'.$body.'</svg>';}
function smhome_card($title,$text,$url,$icon,$tag,$main=false){echo '<a class="sm-card '.($main?'main':'').'" href="'.smhome_h(smhome_url($url)).'"><span class="sm-ico">'.smhome_icon($icon).'</span><span><h4>'.smhome_h($title).'</h4><p>'.smhome_h($text).'</p><em>'.smhome_h($tag).'</em></span></a>';}
$sections=[];
if (plugin_schoolmanager_feature_enabled('tickets') && $canTickets) {$sections[plugin_schoolmanager_tr('support_tickets','Support and tickets')]=[
[plugin_schoolmanager_tr('menu_create_ticket'),plugin_schoolmanager_tr('home_create_ticket_desc','Guided form for teachers and technicians.'),'/plugins/schoolmanager/front/nueva_incidencia.php','ticket',plugin_schoolmanager_tr('support','Support'),true],
[plugin_schoolmanager_tr('menu_my_requests'),plugin_schoolmanager_tr('home_my_requests_desc','Check status, replies and resolution.'),'/plugins/schoolmanager/front/mis_solicitudes.php','check',plugin_schoolmanager_tr('tracking','Tracking'),false],
[plugin_schoolmanager_tr('menu_notices'),plugin_schoolmanager_tr('home_notices_desc','New replies, resolved requests and warnings.'),'/plugins/schoolmanager/front/avisos.php','bell',plugin_schoolmanager_tr('notices','Notices'),false]];}
$inventory=[]; if (plugin_schoolmanager_feature_enabled('assets') && $canAssets) {$inventory[]=[plugin_schoolmanager_tr('menu_create_asset'),plugin_schoolmanager_tr('home_asset_create_desc','Create computers, monitors, printers, network devices and peripherals.'),'/plugins/schoolmanager/front/nuevo_activo.php','plus',plugin_schoolmanager_tr('create','Create'),true]; $inventory[]=[plugin_schoolmanager_tr('menu_assets'),plugin_schoolmanager_tr('home_assets_desc','Search and edit existing assets.'),'/plugins/schoolmanager/front/gestion_activos.php','tools',plugin_schoolmanager_tr('edit','Edit'),true];}
if (plugin_schoolmanager_feature_enabled('stock') && $canStock) {$inventory[]=[plugin_schoolmanager_tr('menu_stock'),plugin_schoolmanager_tr('home_stock_desc','Manage consumables, cartridges and spare parts.'),'/plugins/schoolmanager/front/stock_glpi.php','stock',plugin_schoolmanager_tr('stock','Stock'),true];}
if ($inventory) $sections[plugin_schoolmanager_tr('inventory_assets','Inventory and assets')]=$inventory;
$loc=[]; if(plugin_schoolmanager_feature_enabled('plans')) $loc[]=[plugin_schoolmanager_tr('menu_plan'),plugin_schoolmanager_tr('home_plan_desc','Interactive map with rooms and building selector.'),'/plugins/schoolmanager/front/selector.php','map',plugin_schoolmanager_tr('plans','Maps'),true]; if(plugin_schoolmanager_feature_enabled('classrooms')) $loc[]=[plugin_schoolmanager_tr('menu_classrooms'),plugin_schoolmanager_tr('home_classrooms_desc','Responsive list of rooms and GLPI location IDs.'),'/plugins/schoolmanager/front/aulas.php','list',plugin_schoolmanager_tr('classrooms_label','Classrooms'),false]; if($loc) $sections[plugin_schoolmanager_tr('locations_rooms','Locations and classrooms')]=$loc;
$tic=[]; if(plugin_schoolmanager_feature_enabled('tic_panel') && ($canAssets || $canStock || $isTicTech || $canSuper)) $tic[]=[plugin_schoolmanager_tr('menu_tic_panel'),plugin_schoolmanager_tr('home_tic_desc','Dashboard for open tickets, assignments and stock.'),'/plugins/schoolmanager/front/panel_tic.php','chart',plugin_schoolmanager_tr('technical','Technical'),true]; if(plugin_schoolmanager_feature_enabled('tic_assignment_rules') && $canTicAssign) $tic[]=[plugin_schoolmanager_tr('menu_tic_rules'),plugin_schoolmanager_tr('home_rules_desc','Automatic assignment rules by room, floor or building.'),'/plugins/schoolmanager/front/asignaciones_tic.php','tools',plugin_schoolmanager_tr('it_admin','IT admin'),false]; if($tic) $sections[plugin_schoolmanager_tr('it_panel','IT panel')]=$tic;
$settings=[]; if($canSuper){$settings[]=[plugin_schoolmanager_tr('menu_config'),plugin_schoolmanager_tr('home_settings_desc','Initial setup, branding, modules, maps and rooms.'),'/plugins/schoolmanager/front/instalacion.php','tools',plugin_schoolmanager_tr('settings','Settings'),true]; if(plugin_schoolmanager_feature_enabled('file_editor')) $settings[]=[plugin_schoolmanager_tr('menu_files'),plugin_schoolmanager_tr('home_files_desc','Advanced internal file editor.'),'/plugins/schoolmanager/front/archivos.php','note',plugin_schoolmanager_tr('advanced','Advanced'),false];} if(plugin_schoolmanager_feature_enabled('versions')) $settings[]=[plugin_schoolmanager_tr('menu_versions'),plugin_schoolmanager_tr('home_versions_desc','Plugin documentation and version notes.'),'/plugins/schoolmanager/front/versiones.php','clock',plugin_schoolmanager_tr('docs','Docs'),false]; $settings[]=[plugin_schoolmanager_tr('credits'),plugin_schoolmanager_tr('home_credits_desc','Credits and GPLv3+ license.'),'/plugins/schoolmanager/front/creditos.php','note',plugin_schoolmanager_tr('credits','Credits'),false]; if($settings) $sections[plugin_schoolmanager_tr('plugin_settings','Plugin settings')]=$settings;
$modeText = $isAdminTic ? plugin_schoolmanager_tr('mode_it_admin','IT admin mode') : ($mode==='tecnico' ? plugin_schoolmanager_tr('mode_it_technician','IT technician mode') : plugin_schoolmanager_tr('mode_teacher','Teacher mode'));
?>
<style>
.sm-home{--navy:var(--sm-primary,#07384d);--teal:var(--sm-secondary,#075d61);--red:var(--sm-accent,#b6252b);--soft:var(--sm-soft,#f4fafc);--line:#d7e6ec;--muted:#607582;max-width:1500px;margin:0 auto;padding:clamp(12px,2vw,24px);font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--navy)}.sm-hero{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:center;border:1px solid var(--line);border-radius:32px;background:linear-gradient(135deg,#fff,var(--soft));padding:clamp(18px,3vw,34px);box-shadow:0 24px 60px rgba(7,56,77,.09);margin-bottom:22px}.sm-brand{display:grid;grid-template-columns:auto 1fr;gap:26px;align-items:center}.sm-logo{width:min(240px,22vw);max-height:130px;object-fit:contain;background:transparent}.sm-kicker{font-size:14px;font-weight:950;color:var(--red);letter-spacing:.12em;text-transform:uppercase}.sm-hero h1{font-size:clamp(44px,7vw,92px);line-height:.94;letter-spacing:-.065em;margin:6px 0 8px}.sm-hero p{font-size:clamp(17px,1.4vw,22px);font-weight:850;color:var(--muted);max-width:720px;margin:0}.sm-status{display:flex;gap:10px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.sm-pill{display:inline-flex;align-items:center;gap:8px;border:1px solid var(--line);background:#fff;border-radius:999px;padding:12px 16px;font-weight:950}.sm-dot{width:12px;height:12px;border-radius:50%;background:#21c27a;box-shadow:0 0 0 7px rgba(33,194,122,.14)}.sm-layout{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:26px}.sm-panel,.sm-section{border:1px solid var(--line);border-radius:28px;background:rgba(255,255,255,.95);box-shadow:0 18px 44px rgba(7,56,77,.06);padding:24px}.sm-section{margin-bottom:22px}.sm-title{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:18px}.sm-title h2{margin:0;font-size:26px;letter-spacing:-.03em}.sm-section h3{margin:0 0 24px;font-size:26px;letter-spacing:-.03em}.sm-title small{font-weight:850;color:var(--muted)}
.sm-section h3:after{content:"";display:block;width:64px;height:3px;border-radius:999px;background:linear-gradient(90deg,var(--red),rgba(182,37,43,.15));margin-top:10px}
.sm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(265px,1fr));gap:14px}.sm-card{display:grid;grid-template-columns:60px 1fr;gap:16px;align-items:center;border:1px solid var(--line);border-radius:22px;background:#fff;color:var(--navy)!important;text-decoration:none;padding:18px;min-height:144px;transition:.18s ease;box-shadow:0 10px 26px rgba(7,56,77,.04)}.sm-card:hover{transform:translateY(-4px);border-color:var(--red);box-shadow:0 20px 42px rgba(182,37,43,.12);text-decoration:none}.sm-card.main{background:linear-gradient(135deg,#fff,#fff8f8)}.sm-ico{width:58px;height:58px;border-radius:19px;display:grid;place-items:center;background:#eef8fb;color:var(--navy);transition:.18s ease}.sm-card:hover .sm-ico{background:var(--red);color:#fff}.sm-svg{width:30px;height:30px;stroke:currentColor;stroke-width:2.15;stroke-linecap:round;stroke-linejoin:round;fill:none}.sm-card h4{margin:0 0 6px;font-size:22px;line-height:1.05}.sm-card p{margin:0;font-weight:820;color:var(--muted);line-height:1.25}.sm-card em{display:inline-flex;margin-top:10px;font-style:normal;border:1px solid #f1c7ca;background:#fff5f5;color:#991b1b;border-radius:999px;padding:5px 9px;font-weight:950;font-size:12px}.sm-actions{display:grid;gap:14px}.sm-action{display:flex;align-items:center;justify-content:space-between;gap:14px;border:1px solid var(--line);border-radius:18px;padding:16px 16px;background:#fff;color:var(--navy)!important;font-weight:950;text-decoration:none;transition:.16s}.sm-action:hover{transform:translateX(4px);border-color:var(--red);background:#fff8f8;text-decoration:none}.sm-notice{border:1px solid #f0d483;background:#fff8ea;border-radius:20px;padding:18px;color:#765800;font-weight:850;line-height:1.45;margin-bottom:18px}.sm-panel > .sm-section:last-child{margin-bottom:0}@media(max-width:1180px){.sm-layout{grid-template-columns:1fr}.sm-hero{grid-template-columns:1fr}.sm-status{justify-content:flex-start}}@media(max-width:700px){.sm-home{padding:0 14px}.sm-brand{grid-template-columns:1fr}.sm-logo{width:210px}.sm-card{grid-template-columns:54px 1fr}.sm-ico{width:52px;height:52px}.sm-hero,.sm-panel,.sm-section{padding:20px}.sm-layout{gap:18px}}
</style>
<div class="sm-home schoolmanager-configured">
<section class="sm-hero"><div class="sm-brand"><img class="sm-logo" src="<?= smhome_h($logoUrl) ?>" alt="<?= smhome_h(plugin_schoolmanager_tr('logo_alt','Plugin logo')) ?>" onerror="this.onerror=null;this.src='<?= smhome_h(($CFG_GLPI['root_doc'] ?? '') . '/plugins/schoolmanager/logo.png?v=' . rawurlencode((string)@filemtime(__DIR__ . '/../logo.png'))) ?>';"><div><div class="sm-kicker"><?= smhome_h(plugin_schoolmanager_tr('plugin_kicker','School management for GLPI')) ?></div><h1><?= smhome_h(plugin_schoolmanager_app_name()) ?></h1><p><?= smhome_h($mode === 'tecnico' ? plugin_schoolmanager_tr('home_subtitle_tech','Technical panel for support, inventory, locations and administration.') : plugin_schoolmanager_tr('home_subtitle_teacher','Teacher panel for creating tickets and checking school rooms.')) ?></p></div></div><div class="sm-status"><span class="sm-pill"><i class="sm-dot"></i><?= smhome_h(plugin_schoolmanager_tr('glpi_active','GLPI active')) ?></span><span class="sm-pill"><?= smhome_h($modeText) ?></span><span class="sm-pill">v<?= smhome_h($version) ?></span></div></section>
<section class="sm-layout"><main class="sm-panel"><div class="sm-title"><div><h2><?= smhome_h(plugin_schoolmanager_tr('management_panel','Management panel')) ?></h2><small><?= smhome_h(plugin_schoolmanager_tr('home_panel_desc','Separate blocks for support, inventory, classrooms and settings.')) ?></small></div></div><?php foreach($sections as $title=>$cards): if(empty($cards)) continue; ?><section class="sm-section"><h3><?= smhome_h($title) ?></h3><div class="sm-grid"><?php foreach($cards as $c) smhome_card($c[0],$c[1],$c[2],$c[3],$c[4],$c[5]); ?></div></section><?php endforeach; ?></main><aside class="sm-panel"><div class="sm-title"><div><h2><?= smhome_h(plugin_schoolmanager_tr('quick_access','Quick access')) ?></h2><small><?= smhome_h(plugin_schoolmanager_tr('quick_access_desc','Most common actions for your active profile.')) ?></small></div></div><?php if($mode !== 'tecnico'): ?><div class="sm-notice"><?= smhome_h(plugin_schoolmanager_tr('teacher_notice','This profile can create tickets and check rooms/maps. Inventory editing is hidden to avoid accidental changes.')) ?></div><?php endif; ?><div class="sm-actions"><?php if(plugin_schoolmanager_feature_enabled('tickets') && $canTickets): ?><a class="sm-action" href="<?= smhome_h(smhome_url('/plugins/schoolmanager/front/nueva_incidencia.php')) ?>"><?= smhome_icon('ticket') ?> <?= smhome_h(plugin_schoolmanager_tr('menu_create_ticket')) ?><b>›</b></a><?php endif; ?><?php if(plugin_schoolmanager_feature_enabled('stock') && $canStock): ?><a class="sm-action" href="<?= smhome_h(smhome_url('/plugins/schoolmanager/front/stock_glpi.php')) ?>"><?= smhome_icon('stock') ?> <?= smhome_h(plugin_schoolmanager_tr('menu_stock')) ?><b>›</b></a><?php endif; ?><?php if(plugin_schoolmanager_feature_enabled('assets') && $canAssets): ?><a class="sm-action" href="<?= smhome_h(smhome_url('/plugins/schoolmanager/front/gestion_activos.php')) ?>"><?= smhome_icon('tools') ?> <?= smhome_h(plugin_schoolmanager_tr('menu_assets')) ?><b>›</b></a><?php endif; ?><?php if(plugin_schoolmanager_feature_enabled('plans')): ?><a class="sm-action" href="<?= smhome_h(smhome_url('/plugins/schoolmanager/front/selector.php')) ?>"><?= smhome_icon('map') ?> <?= smhome_h(plugin_schoolmanager_tr('menu_plan')) ?><b>›</b></a><?php endif; ?><?php if($canSuper): ?><a class="sm-action" href="<?= smhome_h(smhome_url('/plugins/schoolmanager/front/instalacion.php')) ?>"><?= smhome_icon('tools') ?> <?= smhome_h(plugin_schoolmanager_tr('menu_config')) ?><b>›</b></a><?php endif; ?></div></aside></section>
</div>
<?php Html::footer(); ?>
